# Generated by Django 4.2.3 on 2023-07-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_reserva_data_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_reserva',
        ),
    ]
